name: Test Zimtohrli

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    if: '! github.event.pull_request.draft'

    steps:
    - name: Install dependencies
      run: sudo apt install -y libogg-dev libvorbis-dev libflac-dev cmake ninja-build libasound2-dev libglfw3-dev libopus-dev
    - name: Install modern xxd
      run: (curl -O http://ftp.us.debian.org/debian/pool/main/v/vim/xxd_9.0.1378-2_amd64.deb && sudo dpkg -i xxd_9.0.1378-2_amd64.deb)
    - name: Check out code
      uses: actions/checkout@v3
    - name: Configure
      run: ./configure.sh
    - name: Build
      run: (cd build && env ninja)
    - name: Test
      run: (cd build && env ctest --output-on-failure)
